---
- name: Run System Hardening (Common Entry Point)
  hosts: all
  become: true
  gather_facts: false

  vars:
    # Default values, in case survey doesn't pass anything
    run_modes: "{{ run_modes | default(['ntp']) }}"
    # Read from both formats to support old and new surveys
    os_type: >-
      {{ (os_type | default(None)) 
         or (os | default(None)) 
         or (os_type_survey | default(None)) 
         or (lookup('vars', 'os_type_input', default=None)) 
         or (lookup('vars', 'os_type_from_survey', default=None)) 
         or (vars['os-type'] | default('generic')) }}

  roles:
    - role: system_hardening_common
