ntp_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
password_minlen: 8
password_maxlen: 16
kerberos_authentication: yes
rsa_auth: yes
banner: "/etc/issue"
banner_text: "Chanky's custom ------>>> Authorized access only. All activity may be monitored and reported."
timestamp: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"
sshd_config_path: "/etc/ssh/sshd_config"
ntp_conf_path: /etc/ntp.conf