---
# NTP for Linux and Unix (AIX, Solaris, HP-UX)
- name: Include NTP configuration (Linux)
  include_tasks: ntp.yml
  when: "'ntp' in run_modes"

- name: Include NTP configuration (Unix)
  include_tasks: ntp_unix.yml
  when: "'ntp_unix' in run_modes"

# Password policy for Linux and Unix (AIX, Solaris, HP-UX)
- name: Include Password policy configuration (Linux)
  include_tasks: password_policy.yml
  when: "'password_policy' in run_modes"

- name: Include Password policy configuration (Unix)
  include_tasks: password_policy_unix.yml
  when: "'password_policy_unix' in run_modes"

# Kerberos, RSA, and Banner config setup for Linux and Unix (AIX, Solaris, HP-UX)
- name: Include Kerberos, RSA, Banner configuration (Linux)
  include_tasks: kerberos_rsa_banner.yml
  when: "'kerberos_rsa_banner' in run_modes"

- name: Include Kerberos, RSA, Banner configuration (Unix)
  include_tasks: kerberos_rsa_banner_unix.yml
  when: "'kerberos_rsa_banner_unix' in run_modes"
