---

- name: Include NTP configuration
  include_tasks: ntp.yml
  when: run_mode == 'ntp'

- name: Include Password policy configuration
  include_tasks: password_policy.yml
  when: run_mode == 'password_policy'

- name: Include Kerberos, RSA, Banner configuration
  include_tasks: kerberos_rsa_banner.yml
  when: run_mode == 'k_r_b'